/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author nikolinatomasevic
 */
public class FrmKonfiguracijaBazePodataka extends javax.swing.JDialog {

	/**
	 * Creates new form FrmKonfiguracijaBazePodataka
	 */
	public FrmKonfiguracijaBazePodataka(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		pripremiFormu();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtUser = new javax.swing.JTextField();
		txtPassword = new javax.swing.JTextField();
		btnSacuvaj = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Konfiguracija baze podataka");

		jLabel1.setText("USER:");

		jLabel2.setText("PASSWORD:");

		btnSacuvaj.setText("Sacuvaj");
		btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSacuvajActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel2)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(82, 82, 82)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(txtPassword).addComponent(txtUser).addComponent(btnSacuvaj,
												javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(35, 35, 35)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(btnSacuvaj).addContainerGap(40, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSacuvajActionPerformed
		try {
			String user = txtUser.getText().trim();
			String password = txtPassword.getText().trim();
			if (user.isEmpty() || password.isEmpty()) {
				JOptionPane.showMessageDialog(this, "Polja ne smeju biti prazna", "Greska", JOptionPane.ERROR_MESSAGE);
				return;
			}
			Properties properties = new Properties();
			properties.load(new FileInputStream("config/dbconfig.properties"));
			properties.setProperty("user", user);
			properties.setProperty("password", password);
			properties.store(new FileOutputStream("config/dbconfig.properties"), null);
			JOptionPane.showMessageDialog(this, "Promene su uspesno sacuvane.");
		} catch (FileNotFoundException ex) {
			ex.printStackTrace();
		} catch (IOException ex) {
			ex.printStackTrace();
		}
	}// GEN-LAST:event_btnSacuvajActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnSacuvaj;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField txtPassword;
	private javax.swing.JTextField txtUser;
	// End of variables declaration//GEN-END:variables

	private void pripremiFormu() {
		try {
			Properties properties = new Properties();
			properties.load(new FileInputStream("config/dbconfig.properties"));
			txtUser.setText(properties.getProperty("user"));
			txtPassword.setText(properties.getProperty("password"));
		} catch (FileNotFoundException ex) {
			ex.printStackTrace();
		} catch (IOException ex) {
			ex.printStackTrace();
		}
	}
}
